name: 'Kubectl for Self Runner'
description: 'The kubectl command line with temp config as a GitHub Action'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'black'
inputs:
  kubeconfig:
    description: 'base64 encoded .kube/config'
